# Generated by Django 5.2.6 on 2026-03-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_financialyeardata_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='high_52w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
