# Generated by Django 5.2.6 on 2026-03-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_instrument_high_52w'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('stock_etf', 'Stock/ETF'), ('mf', 'Mutual Fund'), ('coin', 'Coin'), ('nps', 'NPS')], default='stock_etf', max_length=20),
        ),
    ]
