# Generated by Django 5.2.6 on 2026-03-30 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_instrument_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('isin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('amc', models.CharField(blank=True, max_length=100, null=True)),
                ('nav', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='category',
        ),
        migrations.CreateModel(
            name='MFTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('units', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_transactions', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mutualfund')),
            ],
        ),
        migrations.CreateModel(
            name='MFPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_nav', models.DecimalField(decimal_places=4, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_portfolios', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mutualfund')),
            ],
            options={
                'unique_together': {('user', 'fund')},
            },
        ),
    ]
