# Generated by Django 5.2.6 on 2026-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mutualfund_remove_instrument_category_mftransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfportfolio',
            name='realized_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='prev_nav',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
