# Generated by Django 5.2.6 on 2026-03-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_mfportfolio_realized_profit_mutualfund_prev_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='mftransaction',
            name='remaining_units',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
