# Generated by Django 5.2.6 on 2026-03-31 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_coin_cointransaction_coinportfolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nav', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('prev_nav', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('units', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date', models.DateField()),
                ('remaining_units', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.npsfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NPSPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_nav', models.DecimalField(decimal_places=4, max_digits=20)),
                ('realized_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.npsfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fund')},
            },
        ),
    ]
