# Generated by Django 5.2.6 on 2026-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fixedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
