# Generated by Django 5.2.6 on 2026-04-01 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fixedasset_maturity_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('Plot', 'Plot'), ('Flat', 'Flat'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Land', 'Land'), ('Commercial', 'Commercial Unit'), ('Other', 'Other Physical Asset')], default='Other', max_length=50)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
