# Generated by Django 5.2.6 on 2026-04-01 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_otherasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Home', 'Home Loan'), ('Car', 'Car Loan'), ('Personal', 'Personal Loan'), ('Education', 'Education Loan'), ('Gold', 'Gold Loan'), ('Other', 'Other Loan')], default='Personal', max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_type', models.CharField(choices=[('Reducing', 'Reducing'), ('Flat', 'Flat')], default='Reducing', max_length=20)),
                ('tenure_months', models.IntegerField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest_lock', models.CharField(choices=[('Fixed', 'Fixed'), ('Floating', 'Floating')], default='Fixed', max_length=20)),
                ('next_emi_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('EMI', 'EMI'), ('Prepayment', 'Prepayment')], default='EMI', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.loan')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
