# Generated by Django 5.2.6 on 2026-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_loan_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equity_brokerage_pct',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='equity_fixed_charge',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='initial_investment_limit',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='intraday_brokerage_pct',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='intraday_fixed_charge',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
