# Generated by Django 5.2.6 on 2026-04-02 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_profile_equity_brokerage_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFSIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sip_date', models.IntegerField(help_text='Day of the month (1-28)')),
                ('next_execution_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mutualfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_sips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
