# Generated by Django 5.2.6 on 2026-04-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_mfsip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='asset_type',
            field=models.CharField(choices=[('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit'), ('PPF', 'Public Provident Fund'), ('EPF', 'Employee Provident Fund'), ('Other', 'Other Fixed Asset')], default='FD', max_length=20),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='monthly_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='next_deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='tenure_years',
            field=models.IntegerField(default=1),
        ),
    ]
