# Generated by Django 5.2.6 on 2026-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fixedasset_asset_type_fixedasset_monthly_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equity_brokerage_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='equity_fixed_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intraday_brokerage_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intraday_fixed_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
