# Generated by Django 5.2.6 on 2026-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_profile_equity_brokerage_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketticker',
            name='percent_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
