# Generated by Django 5.2.6 on 2026-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_portfoliovaluehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='coin_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='coin_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='mf_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='mf_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='nps_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='nps_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='stock_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='stock_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
