# Generated by Django 5.2.6 on 2026-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_portfoliovaluehistory_coin_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
