# Generated by Django 5.2.6 on 2026-04-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_portfoliovaluehistory_net_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='nifty_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
