# Generated by Django 5.2.6 on 2026-04-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_portfoliovaluehistory_nifty_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company_work', models.TextField(help_text='What company does – short text')),
                ('notes', models.TextField(help_text='Post / Analysis')),
                ('advise', models.CharField(choices=[('APPLY', 'Apply'), ('NON_APPLY', 'Non Apply'), ('WAITING', 'Waiting')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['-start_date'],
            },
        ),
    ]
