# Generated by Django 5.2.6 on 2026-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_ipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
