# Generated by Django 5.2.6 on 2026-04-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_instrument_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='sector',
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to_family', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'family_user')},
            },
        ),
    ]
