# Generated by Django 5.2.6 on 2026-04-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='tenure_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='equity_brokerage_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.02, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intraday_brokerage_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.02, max_digits=10, null=True),
        ),
    ]
