# Generated by Django 5.2.6 on 2026-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_fixedasset_tenure_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coin_investment_limit',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='mf_investment_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15),
        ),
    ]
