# Generated by Django 5.2.6 on 2026-04-08 14:16

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_profile_coin_investment_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='fd_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='holder_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
