# Generated by Django 5.2.6 on 2026-04-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fixedasset_fd_id_fixedasset_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='core.fixedasset'),
        ),
    ]
