# Generated by Django 5.2.6 on 2026-04-09 05:52

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_fixedasset_parent_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherasset',
            name='asset_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherasset',
            name='holder_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
