# Generated by Django 5.2.6 on 2026-04-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_chatbotknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
