# Generated by Django 5.2.6 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_portfolio_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coin_profit_expectation',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='equity_profit_expectation',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mf_profit_expectation',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=10),
        ),
    ]
