# Generated by Django 5.2.6 on 2026-04-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_profile_coin_profit_expectation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='financial_goal',
            field=models.DecimalField(decimal_places=2, default=10000000.0, max_digits=20),
        ),
    ]
