# Generated by Django 5.2.6 on 2026-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='scheme_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
