# Generated by Django 5.2.6 on 2026-04-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_mutualfund_scheme_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsfund',
            name='scheme_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
