# Generated by Django 5.2.6 on 2026-04-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_npsfund_scheme_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
