# Generated by Django 5.2.6 on 2026-05-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_userreview_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equity_brokerage_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intraday_brokerage_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.2, max_digits=10, null=True),
        ),
    ]
