# Generated by Django 5.2.6 on 2026-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_profile_equity_brokerage_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateaction',
            name='ex_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporateaction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='corporateaction',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
