# Generated by Django 5.2.6 on 2026-05-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_corporateaction_ex_date_corporateaction_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateaction',
            name='action_type',
            field=models.CharField(choices=[('DIVIDEND', 'Dividend Declared'), ('INTERIM_DIVIDEND', 'Interim Dividend'), ('BONUS', 'Bonus Issue'), ('SPLIT', 'Stock Split'), ('RIGHTS_ISSUE', 'Rights Issue'), ('BUYBACK', 'Buyback'), ('MERGER', 'Merger'), ('DEMERGER', 'Demerger'), ('AMALGAMATION', 'Amalgamation'), ('DELISTING', 'Delisting'), ('OPEN_OFFER', 'Open Offer / Takeover'), ('FV_CHANGE', 'Face Value Change / Reverse Split'), ('PREF_ALLOTMENT', 'Preferential Allotment'), ('ESOP', 'ESOP / Share Dilution'), ('SPECIAL_DIVIDEND', 'Special Dividend'), ('SHARE_QUANTITY', 'Share Quantity'), ('SHARE_PRICE', 'Share Price'), ('OWNERSHIP_PCT', 'Ownership Percentage'), ('CASH_BENEFIT', 'Cash Benefit'), ('CO_STRUCTURE', 'Company Structure'), ('TRADING_STATUS', 'Trading / Liquidity Status')], max_length=50),
        ),
    ]
