# Generated by Django 5.2.6 on 2026-05-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_corporateaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateaction',
            name='ex_date',
            field=models.CharField(blank=True, default='Not Yet Declared', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corporateaction',
            name='record_date',
            field=models.CharField(blank=True, default='Not Yet Declared', max_length=50, null=True),
        ),
    ]
