# Generated by Django 5.2.6 on 2026-05-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_corporateaction_ex_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='matched_buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_sells', to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='corporateaction',
            name='ex_date',
            field=models.CharField(blank=True, default='Not Yet Declared', help_text="Enter date (YYYY-MM-DD) or 'Not Yet Declared'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corporateaction',
            name='record_date',
            field=models.CharField(blank=True, default='Not Yet Declared', help_text="Enter date (YYYY-MM-DD) or 'Not Yet Declared'", max_length=50, null=True),
        ),
    ]
