# Generated by Django 5.2.6 on 2026-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_transaction_matched_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ltp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
