# Generated by Django 5.2.6 on 2026-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_portfolio_ltp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trade_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('INTRADAY', 'Intraday')], default='NORMAL', max_length=10),
        ),
    ]
