# Generated by Django 5.2.6 on 2026-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_transaction_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnlstatement',
            name='trade_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('INTRADAY', 'Intraday')], default='NORMAL', max_length=10),
        ),
    ]
