# Generated by Django 5.2.6 on 2026-05-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_profile_equity_brokerage_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('alert_type', models.CharField(blank=True, max_length=50, null=True)),
                ('news_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_alerts', to='core.instrument')),
            ],
        ),
    ]
