# Generated by Django 5.2.6 on 2026-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_newsalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsalert',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
