# Generated by Django 5.2.6 on 2026-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equity_fixed_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intraday_fixed_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
