# Generated by Django 5.2.6 on 2026-05-22 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_profile_equity_fixed_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='SEO-friendly URL identifier. Generated automatically from title.', max_length=255, unique=True)),
                ('content', models.TextField(help_text='The body of the blog post. HTML or plain text.')),
                ('excerpt', models.TextField(blank=True, help_text='A short summary of the post displayed on the list page.', null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Upload an image for the post.', null=True, upload_to='blog_images/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an external image URL if not uploading.', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags (e.g. Stocks, Mutual Funds, Macroeconomy)', max_length=255, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
