# Generated by Django 5.2.6 on 2026-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_idempotencykey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('RENTAL_INCOME', 'Rental Income'), ('INTEREST_INCOME', 'Interest Income'), ('DIVIDEND_INCOME', 'Dividend Income'), ('OTHER_INCOME', 'Other Income'), ('FOOD', 'Food'), ('GROCERIES', 'Groceries & Vegetables'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('TRANSPORTATION', 'Transportation'), ('MEDICAL', 'Medical'), ('ENTERTAINMENT', 'Entertainment / Movies'), ('SHOPPING', 'Shopping'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('DAILY_EXPENSE', 'Daily Expense'), ('OTHER_EXPENSE', 'Other Expense'), ('SIP', 'SIP'), ('MUTUAL_FUNDS', 'Mutual Funds'), ('STOCKS', 'Stocks'), ('FD', 'Fixed Deposit (FD)'), ('PPF', 'PPF'), ('EPF', 'EPF/PF'), ('NPS', 'NPS'), ('BONDS', 'Bonds'), ('GOLD', 'Gold'), ('REAL_ESTATE', 'Real Estate'), ('OTHER_INVESTMENTS', 'Other Investments')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_type',
            field=models.CharField(choices=[('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit'), ('PPF', 'PPF'), ('EPF', 'EPF/PF'), ('Other', 'Other Fixed Asset')], default='FD', max_length=20),
        ),
    ]
