# Generated by Django 5.2.6 on 2026-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_cashflowentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
