# Generated by Django 5.2.6 on 2026-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_blogpost_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherasset',
            old_name='current_value',
            new_name='actual_market_value',
        ),
        migrations.AlterField(
            model_name='otherasset',
            name='actual_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='otherasset',
            name='expected_appreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
