# Generated by Django 5.2.6 on 2026-06-19 16:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_missinginstrumentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('business_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('other_taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('agricultural_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('hra_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('rent_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('section_80c', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('section_80d', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('section_80ccd1b', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('section_80g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'financial_year')},
            },
        ),
    ]
