# Generated by Django 5.2.6 on 2026-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_savedcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(max_length=20, unique=True)),
                ('scheme_name', models.CharField(max_length=300)),
                ('isin_growth', models.CharField(blank=True, max_length=50, null=True)),
                ('isin_div_reinvestment', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
