# Generated by Django 5.2.6 on 2026-07-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_incometaxdemand_incometaxdividend_incometaxequity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxdemand',
            name='assessment_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incometaxdividend',
            name='isin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxequity',
            name='isin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxprofile',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxprofile',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incometaxprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxprofile',
            name='pan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incometaxrefund',
            name='assessment_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incometaxtaxpaid',
            name='bsr_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxtaxpaid',
            name='challan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxtds',
            name='quarter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxtds',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxtds',
            name='tan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
