# Generated by Django 5.2.6 on 2026-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_incometaxdemand_assessment_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='symbol',
            field=models.CharField(blank=True, help_text='NSE/BSE Symbol if listed', max_length=50, null=True),
        ),
    ]
