# Generated by Django 5.2.6 on 2026-07-08 07:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_ipo_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxdemand',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxdividend',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxequity',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxinterest',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxmutualfund',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxother',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxprofile',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxrefund',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxsalary',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxsft',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxtaxpaid',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='incometaxtds',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
        migrations.AlterField(
            model_name='usertaxprofile',
            name='financial_year',
            field=models.CharField(max_length=15, validators=[core.models.validate_fy_format]),
        ),
    ]
