# Generated by Django 5.2.6 on 2026-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_incometaxdemand_financial_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True if IPO is active on registrar portal'),
        ),
        migrations.AddField(
            model_name='ipo',
            name='is_synced_from_registrar',
            field=models.BooleanField(default=False, help_text='True if dynamically synced from registrar'),
        ),
        migrations.AddField(
            model_name='ipo',
            name='registrar_company_id',
            field=models.CharField(blank=True, help_text='Registrar internal company ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='registrar_slug',
            field=models.CharField(blank=True, default='mufg', help_text='Registrar slug (e.g. mufg, kfintech)', max_length=50),
        ),
    ]
