# Generated by Django 5.2.6 on 2026-07-11 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='salon/blogs/')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salon Blog',
                'verbose_name_plural': 'Salon Blogs',
                'db_table': 'salon_blogs',
            },
        ),
        migrations.CreateModel(
            name='SalonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salon Category',
                'verbose_name_plural': 'Salon Categories',
                'db_table': 'salon_categories',
            },
        ),
        migrations.CreateModel(
            name='SalonGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g. Hair, Spa, Skin, Bridal, Before After', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='salon/gallery/')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salon Gallery',
                'verbose_name_plural': 'Salon Gallery Images',
                'db_table': 'salon_gallery',
            },
        ),
        migrations.CreateModel(
            name='SalonOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='salon/offers/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salon Offer',
                'verbose_name_plural': 'Salon Offers',
                'db_table': 'salon_offers',
            },
        ),
        migrations.CreateModel(
            name='SalonSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salon/uploads/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('google_map', models.TextField(help_text='Iframe URL or embed code')),
                ('opening_hours', models.TextField()),
            ],
            options={
                'verbose_name': 'Salon Setting',
                'verbose_name_plural': 'Salon Settings',
                'db_table': 'salon_settings',
            },
        ),
        migrations.CreateModel(
            name='SalonStylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.CharField(help_text='e.g. 5 Years', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='salon/stylists/')),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salon Stylist',
                'verbose_name_plural': 'Salon Stylists',
                'db_table': 'salon_stylists',
            },
        ),
        migrations.CreateModel(
            name='SalonTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('review', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='salon/testimonials/')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salon Testimonial',
                'verbose_name_plural': 'Salon Testimonials',
                'db_table': 'salon_testimonials',
            },
        ),
        migrations.CreateModel(
            name='SalonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salon User',
                'verbose_name_plural': 'Salon Users',
                'db_table': 'salon_users',
            },
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='salon/services/')),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.saloncategory')),
            ],
            options={
                'verbose_name': 'Salon Service',
                'verbose_name_plural': 'Salon Services',
                'db_table': 'salon_services',
            },
        ),
        migrations.CreateModel(
            name='SalonAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex/Other', 'Unisex/Other')], max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.salonservice')),
                ('stylist', models.ForeignKey(db_column='stylist_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.salonstylist')),
            ],
            options={
                'verbose_name': 'Salon Appointment',
                'verbose_name_plural': 'Salon Appointments',
                'db_table': 'salon_appointments',
            },
        ),
    ]
