# Generated by Django 5.2.6 on 2026-07-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nse_symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bse_symbol', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('high_52w', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('low_52w', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('book_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('eps', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roe', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('roce', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('dividend_yield', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('intrinsic_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('industry_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promoter_holding', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sales_growth', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('profit_growth', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('foliux_score', models.IntegerField(default=0)),
                ('buy_score', models.IntegerField(default=0)),
                ('valuation_score', models.IntegerField(default=0)),
                ('growth_score', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('operating_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('investing_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('financing_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='screener.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('share_capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reserves', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('borrowings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cwip', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('investments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='screener.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='screener.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opm_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('other_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('profit_before_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('eps', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dividend_payout_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_financials', to='screener.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=50)),
                ('sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opm_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('other_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('profit_before_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('eps', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_results', to='screener.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShareholdingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('promoters', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fiis', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('diis', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('public', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('government', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='screener.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='screener.company')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
