# Generated by Django 5.2.6 on 2026-07-29 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('doc_type', models.CharField(choices=[('annual_report', 'Annual Report'), ('investor_presentation', 'Investor Presentation'), ('concall_transcript', 'Concall Transcript'), ('quarterly_results', 'Quarterly Results')], default='annual_report', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('local_file_path', models.CharField(help_text='Path under G:\\My Drive\\NETPROFIT\\FOLIUX\\screener\\result\\', max_length=500)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 Checksum', max_length=64, null=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_documents', to='screener.company')),
            ],
            options={
                'ordering': ['company', '-financial_year', 'doc_type'],
                'unique_together': {('company', 'financial_year', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='ManagementForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('source_doc_type', models.CharField(default='Annual Report', max_length=100)),
                ('page_number', models.IntegerField(default=1)),
                ('forecast_statement', models.TextField(help_text='Extract sentence e.g. Revenue expected to grow by 15%')),
                ('metric', models.CharField(db_index=True, help_text='e.g. Revenue Growth, EBITDA Margin, EPS, Capacity Expansion', max_length=100)),
                ('target_value', models.CharField(help_text='e.g. 15%, 20%, Completed Jan 2025', max_length=100)),
                ('target_year', models.CharField(db_index=True, help_text='e.g. FY2025', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_forecasts', to='screener.company')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='screener.managementdocument')),
            ],
            options={
                'ordering': ['company', '-financial_year', 'metric'],
            },
        ),
        migrations.CreateModel(
            name='ForecastComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.CharField(help_text='e.g. 16.2%', max_length=100)),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=2, help_text='% difference between target and actual', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('achieved', 'Achieved'), ('partially_achieved', 'Partially Achieved'), ('not_achieved', 'Not Achieved'), ('delayed', 'Delayed'), ('pending', 'Pending')], db_index=True, default='pending', max_length=50)),
                ('delay_months', models.IntegerField(default=0, help_text='Delay in months if applicable')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=90.0, help_text='AI Confidence Score (0-100)', max_digits=5)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='screener.managementforecast')),
            ],
            options={
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_forecasts', models.IntegerField(default=0)),
                ('achieved_count', models.IntegerField(default=0)),
                ('partially_achieved_count', models.IntegerField(default=0)),
                ('not_achieved_count', models.IntegerField(default=0)),
                ('delayed_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('reliability_score_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_delay_months', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ai_credibility_rating', models.CharField(default='High', max_length=50)),
                ('overall_score', models.IntegerField(db_index=True, default=0)),
                ('last_evaluated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_score', to='screener.company')),
            ],
            options={
                'ordering': ['-overall_score', '-reliability_score_percent'],
            },
        ),
    ]
