# Generated by Django 5.2.6 on 2026-07-28 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPITSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'NPITS Config Setting',
                'verbose_name_plural': 'NPITS Config Settings',
            },
        ),
        migrations.CreateModel(
            name='NPITSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('icon_class', models.CharField(blank=True, default='fas fa-microchip', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='npits.npitscategory')),
            ],
            options={
                'verbose_name': 'IT Product Category',
                'verbose_name_plural': 'IT Product Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NPITSArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='npits.npitscategory')),
            ],
            options={
                'verbose_name': 'Buying Guide / Article',
                'verbose_name_plural': 'Buying Guides / Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NPITSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('asin', models.CharField(blank=True, help_text='Amazon ASIN (e.g. B087NYAF9N)', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Main product image URL', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('review_count', models.IntegerField(default=120)),
                ('short_description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications key-values')),
                ('pros', models.JSONField(blank=True, default=list, help_text='List of Pros')),
                ('cons', models.JSONField(blank=True, default=list, help_text='List of Cons')),
                ('capacity', models.CharField(blank=True, help_text='e.g., 256GB, 512GB, 1TB, 2TB', max_length=50)),
                ('amazon_url', models.URLField(blank=True, help_text='Direct Amazon Product URL', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='npits.npitscategory')),
            ],
            options={
                'verbose_name': 'IT Product',
                'verbose_name_plural': 'IT Products',
                'ordering': ['-is_featured', '-rating', '-price'],
            },
        ),
        migrations.CreateModel(
            name='NPITSAffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('amazon', 'Amazon India'), ('flipkart', 'Flipkart'), ('croma', 'Croma'), ('reliance', 'Reliance Digital'), ('vijaysales', 'Vijay Sales')], default='amazon', max_length=50)),
                ('raw_url', models.URLField(max_length=500)),
                ('affiliate_tag', models.CharField(blank=True, help_text='Custom associate tag override', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='npits.npitsproduct')),
            ],
            options={
                'verbose_name': 'Affiliate Link',
                'verbose_name_plural': 'Affiliate Links',
            },
        ),
        migrations.CreateModel(
            name='NPITSSeoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL slug e.g. best-1tb-hdd', max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('h1_title', models.CharField(max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_filter', models.CharField(blank=True, help_text='e.g. 1TB, 512GB', max_length=50)),
                ('featured_products', models.ManyToManyField(blank=True, related_name='seo_landings', to='npits.npitsproduct')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npits.npitscategory')),
            ],
            options={
                'verbose_name': 'SEO Landing Page',
                'verbose_name_plural': 'SEO Landing Pages',
            },
        ),
    ]
