# Generated by Django 5.2.6 on 2026-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npitsproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload local product image file (overrides external URL)', null=True, upload_to='npits/products/'),
        ),
        migrations.AlterField(
            model_name='npitsproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text='Main product external image URL', max_length=500),
        ),
    ]
