<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Foliux.com</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
						padding: 2rem;
						background-color: #f4f7f9;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 2rem;
						border-radius: 12px;
						box-shadow: 0 4px 20px rgba(0,0,0,0.05);
					}
					h1 {
						color: #003D7C;
						margin-top: 0;
					}
					p {
						font-size: 0.9rem;
						color: #666;
						line-height: 1.6;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 2rem;
					}
					th {
						text-align: left;
						padding: 12px;
						border-bottom: 2px solid #eee;
						background: #fafafa;
						font-size: 0.85rem;
						text-transform: uppercase;
						letter-spacing: 0.05em;
					}
					td {
						padding: 12px;
						border-bottom: 1px solid #f0f0f0;
						font-size: 0.9rem;
					}
					tr:hover {
						background-color: #f9f9f9;
					}
					a {
						color: #0056b3;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.footer {
						margin-top: 3rem;
						font-size: 0.8rem;
						color: #999;
						text-align: center;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p>This is a XML Sitemap, meant for consumption by search engines like Google or Bing.<br/>
					You can find more information about XML sitemaps on <a href="http://sitemaps.org">sitemaps.org</a>.</p>
					
					<table>
						<thead>
							<tr>
								<th>URL</th>
								<th>Priority</th>
								<th>Change Freq.</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<a href="{sitemap:loc}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:value-of select="concat(sitemap:priority*100,'%')"/>
									</td>
									<td>
										<xsl:value-of select="sitemap:changefreq"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
					
					<div class="footer">
						Generated by Foliux Investment Tracking System
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
