# Generated by Django 5.2.6 on 2026-07-11 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TailorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Bridal', 'Bridal'), ('Boutique', 'Boutique'), ('Uniform', 'Uniform'), ('Latest Designs', 'Latest Designs')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tailor/gallery/')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Design',
                'verbose_name_plural': 'Gallery Designs',
                'db_table': 'tailor_gallery',
            },
        ),
        migrations.CreateModel(
            name='TailorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, help_text='e.g. 175 cm', max_length=50, null=True)),
                ('chest', models.CharField(blank=True, max_length=50, null=True)),
                ('waist', models.CharField(blank=True, max_length=50, null=True)),
                ('hip', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=50, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=50, null=True)),
                ('neck', models.CharField(blank=True, max_length=50, null=True)),
                ('inseam', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'db_table': 'tailor_measurements',
            },
        ),
        migrations.CreateModel(
            name='TailorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('discount', models.CharField(help_text='e.g. 20% OFF or Flat ₹500 Off', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Offer Coupon',
                'verbose_name_plural': 'Offer Coupons',
                'db_table': 'tailor_offers',
            },
        ),
        migrations.CreateModel(
            name='TailorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('review', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'db_table': 'tailor_reviews',
            },
        ),
        migrations.CreateModel(
            name='TailorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[("Men's Tailoring", "Men's Tailoring"), ("Women's Tailoring", "Women's Tailoring"), ('Other Services', 'Other Services')], max_length=100)),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.CharField(default='fa-scissors', help_text='FontAwesome icon class name', max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tailoring Service',
                'verbose_name_plural': 'Tailoring Services',
                'db_table': 'tailor_services',
            },
        ),
        migrations.CreateModel(
            name='TailorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tailor/uploads/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('google_map', models.TextField()),
            ],
            options={
                'verbose_name': 'Boutique Setting',
                'verbose_name_plural': 'Boutique Settings',
                'db_table': 'tailor_settings',
            },
        ),
        migrations.CreateModel(
            name='TailorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tailor User',
                'verbose_name_plural': 'Tailor Users',
                'db_table': 'tailor_users',
            },
        ),
        migrations.CreateModel(
            name='TailorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('trial_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Trial', 'Trial'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(blank=True, db_column='measurement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailor.tailormeasurement')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='tailor.tailorservice')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tailor.tailoruser')),
            ],
            options={
                'verbose_name': 'Tailor Order',
                'verbose_name_plural': 'Tailor Orders',
                'db_table': 'tailor_orders',
            },
        ),
        migrations.CreateModel(
            name='TailorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Balance', 'Balance'), ('Full', 'Full')], max_length=20)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tailor.tailororder')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'db_table': 'tailor_payments',
            },
        ),
        migrations.CreateModel(
            name='TailorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('home_visit', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='tailor.tailorservice')),
            ],
            options={
                'verbose_name': 'Tailor Appointment',
                'verbose_name_plural': 'Tailor Appointments',
                'db_table': 'tailor_appointments',
            },
        ),
        migrations.AddField(
            model_name='tailormeasurement',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='tailor.tailoruser'),
        ),
    ]
